# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  servicelocator_sln : "vb2ae.ServiceLocator.MSDependencyInjection.sln"
  package_feed: "https://nuget.pkg.github.com/vb2ae/index.json"
  nuget_folder: "\\packages"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Nuget
      run: msbuild ${{env.servicelocator_sln}} /t:package /p:Configuration=Release
      
    - name: publish Nuget Packages to GitHub
      run: dotnet nuget publish ${{env.nuget_folder}} --source ${{env.package_feed}} --api-key ${{secrets.PUBLISH_NUGET_PACKAGE}} --skip-duplicate
      if: github.event_name != 'pull_request'